### ISSUE TITLE
[1.18.2] Crash/Compatibility Issue

### ISSUE THREAD

**Issue by MC-Valdreth** [Janoeo/JER-Integration#14]
Not sure who's end this is on, but JER Integration fails to load with the latest version of Create. It worked on previous versions up to 0.5.0i

JER Integration (jerintegration) encountered an error during the common_setup event phase
java.lang.NoClassDefFoundError: com/simibubi/create/foundation/config/AllConfigs

Crash Report: https://pastebin.com/xWFvbWpd
latest.log: https://pastebin.com/EmDFXLdq

Forge Version: 40.2.4
Minecraft Version: 1.18.2
JER Integration Version: [3.3.2](https://www.curseforge.com/minecraft/mc-mods/jer-integration/files/3943203)

Other Mods Installed: 
Create Version: [1.18.2 v0.5.1b](https://www.curseforge.com/minecraft/mc-mods/create/files/4550986)
Just Enough Items (JEI) Version: [jei-1.18.2-forge-10.2.1.1004.jar](https://www.curseforge.com/minecraft/mc-mods/jei/files/4434393)
Just Enough Resources (JER): [JustEnoughResources-1.18.2-0.14.2.206](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files/4445746)

Original report on their GitHub: https://github.com/Creators-of-Create/Create/issues/4882
